@startuml
class TodolistTableManager{
+ sortTasks()
+ removeTask()
+ addTAsk()
+ editTaskTitle()
+ displayUncompletedTasks()
+ displayCompletedTasks()
+ SaveItemsOfTask()
}

class ToDoListController {}
class Task{}
class ToDoListApp{}
@enduml